# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el script de Python en el contenedor
COPY . /app

# Instalar paquetes necesarios usando pip
RUN pip install --no-cache-dir requests pandas numpy psycopg2-binary

# Comando para ejecutar el script
CMD ["python", "./my_python_etl_capacity.py"]
