apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.0.2.4
      user: root
      port: 22
      keyPath: /home/vagrant/.ssh/id_rsa
    role: controller+worker
  - ssh:
      address: 10.0.2.6
      user: root
      port: 22
      keyPath: /home/vagrant/.ssh/id_rsa
    role: worker
  - ssh:
      address: 10.0.2.5
      user: root
      port: 22
      keyPath: /home/vagrant/.ssh/id_rsa
    role: worker
  - ssh:
      address: 10.0.2.7
      user: root
      port: 22
      keyPath: /home/vagrant/.ssh/id_rsa
    role: worker
  k0s:
    version: null
    versionChannel: stable
    dynamicConfig: false
    config: {}
